// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GoTest2ND string
	GoTests   string
}{
	GoTest2ND: "go_test_2nd",
	GoTests:   "go_tests",
}
